hpgg/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('score.urls')),
]

score/urls.py
from django.urls import path
from . import views

app_name = 'score'

urlpatterns = [
    path('', views.score_view, name='main'),
    path('search', views.search_res, name='result'),
]

score/models.py
from django.db import models

# Create your models here.
    
class SummonerId(models.Model):
    summonerID = models.CharField(max_length=87)
    create_date = models.DateTimeField()

def __str__(self):
        return self.subject

score/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
import requests

#api요청을 위한 header
request_headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9,ko-KR;q=0.8,ko;q=0.7",
    "Accept-Charset": "application/x-www-form-urlencoded; charset=UTF-8",
    "Origin": "https://developer.riotgames.com",
    #여기에 apikey를 넣어준다
    "X-Riot-Token": "RGAPI-f088ed48-0ab7-4b52-af8b-e1cf3b975db6"
}

def score_view(request):
    return render(request, 'score/score_view.html')

def search_res(request):
    summoner_result = {}
    summoner_tier = {}

    summoner_name = request.GET.get('search_text')
    summoner_response = requests.get("https://kr.api.riotgames.com/lol/summoner/v4/summoners/by-name/" + str(summoner_name), headers=request_headers)
    if summoner_response.status_code == requests.codes.not_found:
        return render(request, 'score/404_not_found.html')
    summoner_response = summoner_response.json()

    summoner_info = requests.get("https://kr.api.riotgames.com/lol/league/v4/entries/by-summoner/" + str(summoner_response['id']), headers=request_headers)
    summoner_info = summoner_info.json()
    if not summoner_info :
        return render(request, 'score/no_solorank.html')
    if summoner_info[0]['queueType'] == 'RANKED_FLEX_SR':
        return render(request, 'score/no_solorank.html')
    summoner_result['name'] = summoner_response['name']
    summoner_result['level'] = summoner_response['summonerLevel']
    summoner_result['icon'] = 'https://ddragon.leagueoflegends.com/cdn/13.24.1/img/profileicon/' + str(summoner_response['profileIconId']) + '.png'
    summoner_tier['tier'] = summoner_info[0]['tier']
    summoner_tier['rank'] = summoner_info[0]['rank']
    summoner_tier['wins'] =  summoner_info[0]['wins']
    summoner_tier['losses'] = summoner_info[0]['losses']
    summoner_tier['winrate'] = int(summoner_tier['wins'] / (summoner_info[0]['wins'] + summoner_info[0]['losses']) * 100)

    # sum_result['profileIconId'] = summoners_response['profileIconId']
    return render(request, 'score/search_res.html', {'res': summoner_result, 'tier': summoner_tier})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
    <title>hun.gg</title>
</head>
<body>
    {% include "navbar.html" %}
    {% block content %}
    {% endblock %}
</body>
</html>

templates/navbar.html
{% load static %}
<head>
	<style>
		.logo {
			width: 30%;
			height: 30%;
		}
	</style>
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" display:block href="{% url 'score:main' %}" >
            <img class="logo" src="{% static 'logo_notitle.png' %}"  alt="로고">
        </a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>

templates/score/404_not_found.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>404 Not Found</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            text-align: center;
        }
        .container {
            max-width: 600px;
            margin: 100px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            color: #e44d26;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>404 Not Found</h1>
        <p>해당 소환사가 존재하지 않습니다.</p>
    </div>
</body>
{% endblock %}

templates/score/no_solorank.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Not Found solorank game</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            text-align: center;
        }
        .container {
            max-width: 600px;
            margin: 100px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        h1 {
            color: #e44d26;
        }
		p {
			margin-top: 15px;
		}
    </style>
</head>
<body>
    <div class="container">
        <p>해당 소환사의 최근 솔로랭크게임 횟수가 부족합니다</p>
    </div>
</body>
{% endblock %}

templates/score/score_view.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<img class="logo" src="{% static 'logo_transparent.png' %}" width="100%" height="100%" alt="로고">
<form action="search" method="get" bolder = "1">
    {% csrf_token %}
    <div class="d-flex justify-content-center h-100">
        <div class="search">
            <input type="text" class="search-input" placeholder="소환사명" name="search_text" value="{{search_text}}" autofocus required>
            <input type="submit" class="search-icon" value="GG">
        </div>
    </div>
</form>
{% endblock %}

templates/score/search_card.html
{% load static %}
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'card.css' %}">
</head>
<div class="card-container">
<img src="{{res.icon}}" alt="Spinning glass cube"/>
	<main class="main-content">
	<h1>{{res.name}}</h1>
	<p>솔로랭크<br>{{tier.tier}} {{tier.rank}}</p>
	<div class="flex-row">
		<div class="level-base">
		  <h2>level : {{res.level}}</h2>
		</div>
		<div class="winrate">
		  <p>{{tier.wins}}승 {{tier.losses}}패 ({{tier.winrate}}%)</p>
		</div>
	  </div>
	</main>.
</div>

templates/score/search_res.html
{% extends 'base.html' %}
{%load static%}
{% block content %}
	{% include "score/search_card.html" %}
{% endblock %}